---
name: Destroy Terraform
# configure manual trigger
on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    env:
      STORAGE_ACCOUNT: ${{ vars.STORAGE_ACCOUNT }}
      CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.TENANT_ID }}
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Log into Azure with OIDC integration
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ vars.CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID}}
          tenant-id: ${{ vars.TENANT_ID}}

      - name: Terraform destroy
        run: terraform destroy --auto-approve
