name: Deploy Terraform
on:
  push:
    branches:
      - main

jobs:
  tf:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false
    
    - name: Terraform Init
      id: init
      run: terraform init
