name: Deploy Terraform
on:
  push:
    branches:
      - main

jobs:
  tf:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -no-color
      continue-on-error: false
    
    - name: Terraform Init
      id: init
      run: terraform init
      env:
        ARM_ACCES_KEY: ${{ secrets.ACCESS_KEY}}
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }} # This doesn't have to be a secret. Client IDs are not sensitive.
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID}} 
        ARM_TENANT_ID: ${{ vars.TENANT_ID}}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: false

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false -no-color -out tf.plan
      env:
        ARM_ACCES_KEY: ${{ secrets.ACCESS_KEY}}
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }} # This doesn't have to be a secret. Client IDs are not sensitive.
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID}} 
        ARM_TENANT_ID: ${{ vars.TENANT_ID}}
        continue-on-error: false

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -input=false tf.plan
      env:
        ARM_ACCES_KEY: ${{ secrets.ACCESS_KEY}}
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }} # This doesn't have to be a secret. Client IDs are not sensitive.
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID}}
        ARM_TENANT_ID: ${{ vars.TENANT_ID}}
